import { Link } from "react-router";
import "./Legal.scss";

const TermsOfService = () => {
    return (
        <div className="legal-page">
            <Link to="/" className="legal-page__back">
                &larr; Back to home
            </Link>

            <header className="legal-page__header">
                <h1>Terms of Service</h1>
                <p className="legal-page__updated">Last updated: July 15, 2026</p>
            </header>

            <div className="legal-page__card">
                <p className="legal-page__intro">
                    These Terms of Service ("Terms") govern your use of Resume Doctor. By
                    creating an account or using our services, you agree to these Terms.
                </p>

                <section className="legal-section">
                    <h2>1. Description of Service</h2>
                    <p>
                        Resume Doctor is an AI-powered platform that analyzes resumes against
                        job descriptions to provide an ATS compatibility score, skill-gap
                        analysis, matched/missing keywords, and a personalized interview
                        preparation report including technical and behavioural questions with
                        suggested answers.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>2. Accounts</h2>
                    <p>
                        You must provide accurate information when creating an account and are
                        responsible for maintaining the confidentiality of your login
                        credentials. You are responsible for all activity that occurs under
                        your account.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>3. Acceptable Use</h2>
                    <p>You agree not to:</p>
                    <ul>
                        <li>Upload content that is unlawful, infringing, or contains malware</li>
                        <li>Upload another person's resume or personal data without their consent</li>
                        <li>Attempt to reverse engineer, scrape, or overload our systems</li>
                        <li>Use the service to generate content for fraudulent job applications on someone else's behalf without authorization</li>
                        <li>Resell or redistribute reports generated by the service without our permission</li>
                    </ul>
                </section>

                <section className="legal-section">
                    <h2>4. AI-Generated Content Disclaimer</h2>
                    <p>
                        Resume Doctor's scores, feedback, interview questions, sample answers,
                        and preparation plans are generated by an AI model based on the
                        information you provide. This content is intended to help you prepare
                        and improve — it is <strong>not</strong> a guarantee of interview
                        performance, hiring outcomes, or resume accuracy, and it does not
                        constitute professional career, legal, or employment advice. You are
                        responsible for reviewing and verifying all AI-generated content before
                        relying on it.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>5. Intellectual Property</h2>
                    <p>
                        You retain ownership of the resume, job description, and any other
                        content you upload. By uploading content, you grant us a limited
                        license to process it solely for the purpose of providing the service
                        to you (including sending it to our AI provider for analysis). We own
                        all rights to the Resume Doctor platform, branding, and underlying
                        technology.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>6. Termination</h2>
                    <p>
                        You may stop using the service and delete your account at any time. We
                        may suspend or terminate accounts that violate these Terms, engage in
                        abusive behavior toward our systems, or as required by law.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>7. Limitation of Liability</h2>
                    <p>
                        To the fullest extent permitted by law, Resume Doctor is provided "as
                        is" without warranties of any kind. We are not liable for any indirect,
                        incidental, or consequential damages arising from your use of the
                        service, including outcomes related to job applications or interviews.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>8. Changes to These Terms</h2>
                    <p>
                        We may update these Terms from time to time. We will update the "Last
                        updated" date above when we do. Continued use of Resume Doctor after
                        changes take effect constitutes acceptance of the revised Terms.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>9. Governing Law</h2>
                    <p>
                        These Terms are governed by the laws of India, without regard to
                        conflict of law principles.
                    </p>
                </section>

                <div className="legal-page__contact">
                    <p>
                        Questions about these Terms? Contact us at{" "}
                        <a href="mailto:amanraj01122@gmail.com">amanraj01122@gmail.com</a>
                        .
                    </p>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
